const data_set = {
    abjat : "abjad",
    adpokat : "advokat",
    adesi : "adhesi",
    afdol : "afdal",
    aktip : "aktif",
    aktifitas : "aktivitas",
    aquatik : "akuatik",
    ambeyen : "ambeien",
    alaram : "alarm",
    ambulan : "ambulans",
    amandemen : "amendemen",
    ampibi : "amfibi",
    amoniak : "amonia",
    analisa : "analisis",
    handal : "andal",
    antri : "antre",
    apotik : "apotek",
    artifak : "artefak",
    azas : "asas",
    astronot : "astronout",
    asik : "asyik",
    atheis : "ateis",
    atheisme : "ateisme",
    atlit : "atlet",
    atmosfir : "atmosfer",
    otentik : "autentik",
    adzan : "azan",
    baligh : "balig",
    balsem : "balsam",
    baterei : "baterai",
    brandal : "berandal",
    brantas : "berantas",
    brengsek : "berengsek",
    berfikir : "berpikir",
    bertanggungjawab : "bertanggung jawab",
    bolpen : "bolpoin",
    berankas : "brankas",
    budget : "bujet",
    bowling : "boling",
    borax : "boraks",
    bis : "bus",
    cabe : "cabai",
    capek : "capai",
    cicak : "cecak",
    cidera : "cedera",
    cendikia : "cendekia",
    cendikiawan : "cendekiawan",
    cenderamata : "cendera mata",
    cengkrama : "cengkerama",
    cengkeh : "cengkih",
    coklat : "cokelat",
    daptar : "daftar",
    dasyat : "dahsyat",
    dulu : "dahulu",
    dasbord : "dasbor",
    debitor : "debitur",
    detil : "detail",
    deterjen : "detergen",
    dijit : "digit",
    diagnosa : "diagnosis",
    differensial : "diferensial",
    dollar : "dolar",
    dopping : "doping",
    drem : "drum",
    duren : "durian",
    efektip : "efektif",
    explisit : "eksplisit",
    eksponent : "eksponen",
    eksport : "ekspor",
    expres : "ekspres",
    extra : "ekstra",
    ekstrim : "ekstrem",
    ekuifalen : "ekuivalen",
    elit : "elite",
    hembus : "embus",
    esei : "esai",
    faksimili : "faksimile",
    pebruari : "februari",
    figure : "figur",
    pondasi : "fondasi",
    formil : "formal",
    pospor : "fosfor",
    photo : "foto",
    photokopi : "fotokopi",
    fotosintesa : "fotosintesis",
    fraksinase : "fraksinasi",
    frase : "frasa",
    frekwensi : "frekuensi",
    ghaib : "gaib",
    ghoib : "gaib",
    gengster : "gangster",
    ganjel : "ganjal",
    gatel : "gatal",
    glora : "gelora",
    gladi : "geladi",
    jenius : "genius",
    greget : "gereget",
    giji : "gizi",
    goa : "gua",
    gubug : "gubuk",
    gudek : "gudeg",
    hadist : "hadis",
    hapal : "hafal",
    hakekat : "hakikat",
    angus : "hangus",
    hektar : "hektare",
    herves : "herpes",
    hetrografi : "heterografi",
    hipotesa : "hipotesis",
    history : "histori",
    idil : "idiil",
    ikhram : "ihram",
    ijasah : "ijazah",
    iklas : "ikhlas",
    ihlas : "ikhlas",
    himbau : "imbau",
    import : "impor",
    indera : "indra",
    insyaf : "insaf",
    inten : "intens",
    intisari : "inti sari",
    hisap : "isap",
    istighfar : "istigfar",
    isteri : "istri",
    intemezo : "intermeso",
    ijin : "izin",
    jadual : "jadwal",
    jais : "jaiz",
    jasat : "jasad",
    jamaah : "jemaah",
    jenasah : "jenazah",
    jendral : "jenderal",
    yudo : "judo",
    yunior : "junior",
    yuri : "juri",
    kaedah : "kaidah",
    kaabah : "kakbah",
    kangker : "kanker",
    karna : "karena",
    karir : "karier",
    kharisma : "karisma",
    karnafal : "karnaval",
    kasroh : "kasrah",
    katalisa : "katalisis",
    ketapel : "katapel",
    katagori : "kategori",
    kebon : "kebun",
    kadaluarsa : "kedaluwarsa",
    kadaluwarsa : "kedaluwarsa",
    kedelei : "kedelai",
    klengkeng : "kelengkeng",
    kendor : "kendur",
    katam : "khatam",
    hatam : "khatam",
    kuatir : "khawatir",
    khutbah : "khotbah",
    kyai : "kiai",
    client : "klien",
    keliping : "kliping",
    keloter : "kloter",
    koboy : "koboi",
    komersil : "komersial",
    komplek : "kompleks",
    komplit : "komplet",
    konggres : "kongres",
    konsumtip : "konsumtif",
    koordinir : "koordinasi",
    konsleting : "korsleting",
    kosakata : "kosa kata",
    kreatip : "kreatif",
    kreatifitas : "kreativitas",
    kreditor : "kreditur",
    kwalifikasi : "kualifikasi",
    kwalitas : "kualitas",
    kwantitatif : "kuantitatif",
    kwitansi : "kuitansi",
    lebel : "label",
    lapal : "lafal",
    legalisir : "legalisasi",
    lembap : "lembab",
    litosfir : "litosfer",
    lobang : "lubang",
    maap : "maaf",
    macem : "macam",
    maghrib : "magrib",
    maximum : "maksimum",
    mangkok : "mangkuk",
    mantera : "mantra",
    masal : "massal",
    mesjid : "massjid",
    mempengaruhi : "memengaruhi",
    mengkonsumsi : "mengonsumsi",
    merubah : "mengubah",
    mentri : "menteri",
    mencontek : "menyontek",
    merk : "merek",
    mesosfir : "mesosfer",
    materai : "meterai",
    metoda : "metode",
    miraj : "mikraj",
    missi : "misi",
    miliyar : "miliar",
    mulya : "mulia",
    nahkoda : "nakhoda",
    nafas : "napas",
    nasehat : "nasihat",
    negri : "negeri",
    netto : "neto",
    nomer : "nomor",
    notulen : "notula",
    nopember : "november",
    obyek : "objek",
    obyektif : "objektif",
    ok : "oke",
    omset : "omzet",
    organisir: "organisasi",
    orisinil : "orisinal",
    faham : "paham",
    pait : "pahit",
    palm : "palem",
    pancoran : "pancuran",
    paradox : "paradoks",
    pasport : "paspor",
    pedes : "pedas",
    vermak : "permak",
    pinsil : "pensil",
    presepsi : "persepsi",
    perespektif : "perspektif",
    fikir : "pikir",
    perancis : "prancis",
    presidental : "presidensial",
    produktip : "produktif",
    produktifitas : "produktivitas",
    projek : "proyek",
    propinsi : "provinsi",
    putera : "putra",
    puteri : "putri",
    rame : "ramai",
    rapih : "rapi",
    raport : "rapor",
    reamur : "reaumur",
    respon : "respons",
    resistan : "resistans",
    rematik : "reumatik",
    rejeki : "rezeki",
    resim : "rezim",
    resiko : "risiko",
    rubuh : "roboh",
    ruh : "roh",
    sohih : "sahih",
    seksama : "saksama",
    sambel : "sambal",
    sangsi : "sanksi",
    sastera : "sastra",
    sate : "satai",
    saos : "saus",
    sekedar : "sekadar",
    sekertaris : "sekretaris",
    seprei : "seprai",
    seterika : "setrika",
    strika : "setrika",
    sintesa : "sintesis",
    supir : "sopir",
    standarisasi : "standardisasi",
    statosfir : "statosfer",
    subyek : "subjek",
    survey : "survei",
    sutera : "sutra",
    swis : "swiss",
    sahid : "syahid",
    sawal : "syawal",
    tehnik : "teknik",
    tauladan : "teladan",
    telpon : "telepon",
    tentram : "tenteram",
    termosfir : "termosfer",
    taubat : "tobat",
    transport : "transpor",
    triliyun : "triliun",
    triplek : "tripleks",
    tropi : "trofi",
    umroh : "umrah",
    onta : "unta",
    urgent : "urgen",
    urin : "urine",
    ustadz : "ustaz",
    hutang : "utang",
    varietes : "varietas",
    varitas : "varietas",
    walikota : "wali kota",
    jogjakarta : "yogyakarta",
    judikatif : "yudikatif",
    jaman : "zaman",
    jamrud : "zamrud",

    abrasi : "aberasi",
    absorsi : "absorpsi",
    adap : "adab",
    aditorium : "auditorium",
    admin : "administrator",
    agamis : "agamais",
    ajeg : "ajek",
    ajektif : "adjektif",

    cafetaria : "kafetaria",
    cape : "capai",
    cathering : "catering",
    cengkram : "cengkeram",
    centigram : "sentigram",
    centimeter : "sentimeter",
    central : "sentral",
    chlor : "klor",
    clash : "kles",
    clien : "klien",
    club : "klab",
    debet : "debit",
    defiasi : "deviasi",
    dekrit : "dekret",
    deodorant : "deodoran",
    depo : "depot",
    deputy : "deputi",
    design : "desain",
    despenser : "dispenser",
    destilasi : "distilasi",
    detel : "detail",
    deviden : "dividen",
    dharma : "darma",
    dhuhur : "zuhur",
    donator : "donatur",
    eksibisi : "ekshibisi",
    eksim : "eksem",
    ekwivalen : "ekuivalen",
    elektroda : "elektrode",
    elip : "elips",
    engine : "enjin",
    ensiklopedi : "ensiklopedia",
    ephos : "epos",
    episod : "episode",
    equivalen : "ekuivalen",
    esen : "esens",
    esense : "esens",
    essai : "esai",
    essay : "esai",
    ethanol : "etanol",
    faksinasi : "vaksinasi",
    fakum : "vakum",
    falid : "valid",
    familiar : "familier",
    famplet : "pamflet",
    faqih : "fakih",
    farmakop : "farmakope",
    fas : "vas",
    ferri : "feri",
    filosof : "filsuf",
    galaktose : "galaktosa",
    galery : "galeri",
    geneologi : "genealogi",
    genteng : "genting",
    gep : "gap",
    gepok : "kapok",
    geyser : "geiser",
    gip : "gips",
    glamour : "glamor",
    glondong : "gelondong",
    glosary : "glosarium",
    glukoma : "glaucoma",
    glukose : "glukosa",
    goncang : "guncang",
    grebek : "gerebek",
    grendel : "gerendel",
    gria : "griya",
    hempas : "empas",
    hetrogen : "heterogen",
    hidrolis : "hidraulis",
    higiena : "hygiene",
    himpit : "impit",
    hipermetri : "hypermetropia",
    hipotik : "hipotek",
    hipovitaminose : "hipovitaminosis",
    hirarki : "hierarki",
    hiroglif : "hieroglif",
    hymne : "himne",
    ibtidaiyah : "ibtidaiah",
    iddah : "idah",
    idial : "ideal",
    idiologi : "ideologi",
    ikhwal : "ihwal",
    illusi : "ilusi",
    incognito : "incognito",
    income : "inkam",
    influensa : "influenza",
    inpus : "infus",
    instink : "insting",
    inteligen : "intelijen",
    jagad : "jagat",
    jahiliyah : "jahiliah",
    jeep : "jip",
    jejer : "jajar",
    jemaah : "jamaah",
    zarafah : "jerapah",
    jiujitsu : "jujitsu",
    joging : "jogging",
    joint : "join",
    jubilum : "jubileum",
    jungtur : "junktur",
    jus : "juz",
    kaburasi : "karburasi",
    kaburator : "karburator",
    kaffah : "kafah",
    kahyangan : "kayangan",
    kaleidioskop : "kaleidoskop",
    kalkarim : "kalkarium",
    kamboja : "kemboja",
    kameraman : "kamerawan",
    kameramen : "kamerawan",
    kamuplase : "kamuflase",
    kangguru : "kanguru",
    kantung : "kantong",
    kaos : "kaus",
    kasep : "kasip",
    lajim : "lazim",
    ledeng : "leding",
    almari : "lemari",
    lembab : "lembap",
    leukimia : "leukemia",
    linier : "linear",
    literal : "litoral",
    loby : "lobi",
    lokalisir : "lokalisasi",
    losin : "lusin",
    maag : "mag",
    madzab : "mazhab",
    mafum : "mafhum",
    mahnet : "magnet",
    maisena : "maizena",
    makdum : "makhdum",
    malpraktek : "malapraktik",
    mampet : "mampat",
    manager : "manajer",
    mandeg : "mandek",
    margarine : "margarin",
    marjinal : "marginal",
    mas : "emas",
    nadzar : "nazar",
    nampak : "tampak",
    nenas : "nanas",
    netralisisir : "netralisasi",
    nipas : "nifas",
    okulele : "ukulele",
    opostrop : "apostrof",
    orange : "oranye",
    orkhestra : "orchestra",
    padepokan : "pedepokan",
    palem : "palm",
    pamfelet : "pamflet",
    panili : "vanili",
    paramedik : "paramedis",
    parasit : "parasut",
    peliara : "pelihara",
    pengrajin : "perajin",
    perduli : "peduli",
    philipina : "filipina",
    piara : "pelihara",
    piranti : "peranti",
    plat : "flat",
    plesetan : "pelesetan",
    plesir : "pelesir",
    pleton : "peleton",
    plintir : "pelintir",
    polio : "folio",
    rajia : "razia",
    rangking : "ranking",
    rangsel : "ransel",
    rapal : "lafal",
    rapot : "rapor",
    rasia : "razia",
    rasionil : "rasional",
    realisir : "realisasi",
    rekaat : "rakaat",
    rekruit : "rekrut",
    relif : "relief",
    renaisan : "renaisans",
    rengking : "ranking",
    reptil : "reptilia",
    restauran : "restoran",
    resum : "resume",
    reumatik : "rematik",
    rezki : "rezeki",
    ridho : "rida",
    riil : "real",
    rilai : "relai",
    sahadat : "syahadat",
    saklar : "sakelar",
    sangkalan : "sengkalan",
    sanjak : "sajak",
    sansekerta : "sanskerta",
    saplemen : "suplemen",
    sariawan : "seriawan",
    score : "skor",
    seign : "sein",
    sekolastik : "skolastik",
    sekor : "skor",
    sekta : "sekte",
    sekterian : "sectarian",
    sekuadron : "eskadron",
    sekuler : "secular",
    selektifitas : "selektivitas",
    selinder : "sislinder",
    selulose : "selulosa",
    semanda : "semenda",
    sembrono : "sembrama",
    semedi : "semadi",
    sen : "sein",
    senopati : "senapati",
    sense : "sinse",
    sentausa : "sentosa",
    sentimentil : "sentimental",
    sentra : "sentral",
    sepesial : "special",
    sepesies : "spesies",
    sepionase : "spionase",
    sepiritus : "spiritus",
    seruling : "suling",
    service : "servis",
    setansa : "stanza",
    setriker : "striker",
    seyogyanya : "seyogianya",
    shaf : "saf",
    shampo : "sampo",
    she : "syekh",
    shogun : "syogun",
    shalat : "salat",
    sholat : "salat",
    silahkan : "silakan",
    silaturohmi : "silaturahmi",
    simple : "simpel",
    sindrome : "sindrom",
    sirik : "syirik",
    sirine : "sirene",
    sistim : "sistem",
    skop : "sekop",
    sky : "ski",
    slendro : "selendro",
    sleng : "slang",
    slenk : "slang",
    smash : "smes",
    sodakoh : "sedekah",
    sokhib : "sahib",
    sorban : "serban",
    sorga : "surga",
    spagheti : "spageti",
    species : "spesies",
    srigala : "serigala",
    stagen : "setagen",
    standard : "standar",
    standart : "standar",
    stater : "starter",
    stereotipe : "stereotip",
    sticker : "stiker",
    stip : "setip",
    stir : "setir",
    stock : "stok",
    subsidair : "subsider",
    subtansi : "substansi",
    subtitusi : "substitusi",
    supermasi : "supremasi",
    susastera : "susatra",
    tabligh : "tablig",
    tahta : "takhta",
    tapelak : "taplak",

    faximile: "faksimile",
    inofatif : "inovatif",
    kordinasi: "koordinasi",
    kwarter : "kuarter",
    netralisir: "netralisasi",

    "cap cai" : "capcai",
    "da'i" : "dai",
    "da'wah" : "dakwah",
    "export" : "ekspor",
    "foto copy" : "fotokopi",
    "geladi resik" : "geladi bersih",
    "hal-ihwal" : "hal-hal",
    "hingar-bingar" : "ingar-bingar",
    "i'tibar" : "iktibar",
    "i'tikaf" : "iktikaf",
    "infra merah" : "inframerah",
    "jor-joran" : "jorjoran",
    "ka'bah" : "kakbah",
    "kaca mata" : "kacamata",
    "ma'af" : "maaf",
    "comblang" : "makcomblang",
    "neo-kolonialisme" : "neokolonialisme",
    "non aktif" : "nonaktif",
    "panca indra" : "pancaindra",
    "pas photo" : "pasfoto",
    "sedia kala" : "sediakala",
    "sub bab" : "subbab",
    "sub unit" : "subunit",
    "suka cita" : "sukacita",
    "swa sembada" : "swasembada",
    "syafa'at" : "syafaat",

    "jum'at" : "jumat",
    "tolak ukur" : "tolok ukur",
    "zam-zam" : "zamzam",
    "pasca panen" : "pascapanen",
    "pasca perang" : "pascaperang",
    "pasca sarjana" : "pascasarjana",
    "non blok" : "nonblok",
    "non militer" : "nonmiliter",
    "nara sumber" : "narasumber",
    "foto-model" : "fotomodel",
    "darma siswa" : "darmasiswa",
    "darma wisata" : "darmawisata",
}

const data_collection = [
    "abjat",
    "adpokat",
    "adesi",
    "afdol",
    "aktip",
    "aktifitas",
    "aquatik",
    "ambeyen",
    "alaram",
    "ambulan",
    "amandemen",
    "ampibi",
    "amoniak",
    "analisa",
    "handal",
    "antri",
    "apotik",
    "artifak",
    "azas",
    "astronot",
    "asik",
    "atheis",
    "atheisme",
    "atlit",
    "atmosfir",
    "otentik",
    "adzan",
    "baligh",
    "balsem",
    "baterei",
    "brandal",
    "brantas",
    "brengsek",
    "berfikir",
    "bertanggungjawab",
    "bolpen",
    "berankas",
    "budget",
    "bowling",
    "borax",
    "bis",
    "cabe",
    "capek",
    "cicak",
    "cidera",
    "cendikia",
    "cendikiawan",
    "cenderamata",
    "cengkrama",
    "cengkeh",
    "coklat",
    "daptar",
    "dasyat",
    "dulu",
    "dasbord",
    "debitor",
    "detil",
    "deterjen",
    "dijit",
    "diagnosa",
    "differensial",
    "dollar",
    "dopping",
    "drem",
    "duren",
    "efektip",
    "explisit",
    "eksponent",
    "eksport",
    "expres",
    "extra",
    "ekstrim",
    "ekuifalen",
    "elit",
    "hembus",
    "esei",
    "faksimili",
    "pebruari",
    "figure",
    "pondasi",
    "formil",
    "pospor",
    "photo",
    "photokopi",
    "fotosintesa",
    "fraksinase",
    "frase",
    "frekwensi",
    "ghaib",
    "ghoib",
    "gengster",
    "ganjel",
    "gatel",
    "glora",
    "gladi",
    "jenius",
    "greget",
    "giji",
    "goa",
    "gubug",
    "gudek",
    "hadist",
    "hapal",
    "hakekat",
    "angus",
    "hektar",
    "herves",
    "hetrografi",
    "hipotesa",
    "history",
    "idil",
    "ikhram",
    "ijasah",
    "iklas",
    "ihlas",
    "himbau",
    "import",
    "indera",
    "insyaf",
    "inten",
    "intisari",
    "hisap",
    "istighfar",
    "isteri",
    "intemezo",
    "ijin",
    "jadual",
    "jais",
    "jasat",
    "jamaah",
    "jenasah",
    "jendral",
    "yudo",
    "yunior",
    "yuri",
    "kaedah",
    "kaabah",
    "kangker",
    "karna",
    "karir",
    "kharisma",
    "karnafal",
    "kasroh",
    "katalisa",
    "ketapel",
    "katagori",
    "kebon",
    "kadaluarsa",
    "kadaluwarsa",
    "kedelei",
    "klengkeng",
    "kendor",
    "katam",
    "hatam",
    "kuatir",
    "khutbah",
    "kyai",
    "client",
    "keliping",
    "keloter",
    "koboy",
    "komersil",
    "komplek",
    "komplit",
    "konggres",
    "konsumtip",
    "koordinir",
    "konsleting",
    "kosakata",
    "kreatip",
    "kreatifitas",
    "kreditor",
    "kwalifikasi",
    "kwalitas",
    "kwantitatif",
    "kwitansi",
    "lebel",
    "lapal",
    "legalisir",
    "lembap",
    "litosfir",
    "lobang",
    "maap",
    "macem",
    "maghrib",
    "maximum",
    "mangkok",
    "mantera",
    "masal",
    "mesjid",
    "mempengaruhi",
    "mengkonsumsi",
    "merubah",
    "mentri",
    "mencontek",
    "merk",
    "mesosfir",
    "materai",
    "metoda",
    "miraj",
    "missi",
    "miliyar",
    "mulya",
    "nahkoda",
    "nafas",
    "nasehat",
    "negri",
    "netto",
    "nomer",
    "notulen",
    "nopember",
    "obyek",
    "obyektif",
    "ok",
    "omset",
    "organisir",
    "orisinil",
    "faham",
    "pait",
    "palm",
    "pancoran",
    "paradox",
    "pasport",
    "pedes",
    "vermak",
    "pinsil",
    "presepsi",
    "perespektif",
    "fikir",
    "perancis",
    "presidental",
    "produktip",
    "produktifitas",
    "projek",
    "propinsi",
    "putera",
    "puteri",
    "rame",
    "rapih",
    "raport",
    "reamur",
    "respon",
    "resistan",
    "rematik",
    "rejeki",
    "resim",
    "resiko",
    "rubuh",
    "ruh",
    "sohih",
    "seksama",
    "sambel",
    "sangsi",
    "sastera",
    "sate",
    "saos",
    "sekedar",
    "sekertaris",
    "seprei",
    "seterika",
    "strika",
    "sintesa",
    "supir",
    "standarisasi",
    "statosfir",
    "subyek",
    "survey",
    "sutera",
    "swis",
    "sahid",
    "sawal",
    "tehnik",
    "tauladan",
    "telpon",
    "tentram",
    "termosfir",
    "taubat",
    "transport",
    "triliyun",
    "triplek",
    "tropi",
    "umroh",
    "onta",
    "urgent",
    "urin",
    "ustadz",
    "hutang",
    "varietes",
    "varitas",
    "walikota",
    "jogjakarta",
    "judikatif",
    "jaman",
    "jamrud",

    "jum'at",
    "tolak ukur",
    "zam-zam",
    "pasca panen",
    "pasca perang",
    "pasca sarjana",
    "non blok",
    "non militer",
    "nara sumber",
    "foto-model",
    "darma siswa",
    "darma wisata",

    "abrasi",
    "absorsi",
    "adap",
    "aditorium",
    "admin",
    "agamis",
    "ajeg",
    "ajektif",
    "faximile",
    "inofatif",
    "kordinasi",
    "kwarter",
    "netralisir",

    "cafetaria",
    "cape",
    "cathering",
    "cengkram",
    "centigram",
    "centimeter",
    "central",
    "chlor",
    "clash",
    "clien",
    "club",
    "debet",
    "defiasi",
    "dekrit",
    "deodorant",
    "depo",
    "deputy",
    "design",
    "despenser",
    "destilasi",
    "detel",
    "deviden",
    "dharma",
    "dhuhur",
    "donator",
    "eksibisi",
    "eksim",
    "ekwivalen",
    "elektroda",
    "elip",
    "engine",
    "ensiklopedi",
    "ephos",
    "episod",
    "equivalen",
    "esen",
    "esense",
    "essai",
    "essay",
    "ethanol",
    "faksinasi",
    "fakum",
    "falid",
    "familiar",
    "famplet",
    "faqih",
    "farmakop",
    "fas",
    "ferri",
    "filosof",
    "galaktose",
    "galery",
    "geneologi",
    "genteng",
    "gep",
    "gepok",
    "geyser",
    "gip",
    "glamour",
    "glondong",
    "glosary",
    "glukoma",
    "glukose",
    "goncang",
    "grebek",
    "grendel",
    "gria",
    "hempas",
    "hetrogen",
    "hidrolis",
    "higiena",
    "himpit",
    "hipermetri",
    "hipotik",
    "hipovitaminose",
    "hirarki",
    "hiroglif",
    "hymne",
    "ibtidaiyah",
    "iddah",
    "idial",
    "idiologi",
    "ikhwal",
    "illusi",
    "incognito",
    "income",
    "influensa",
    "inpus",
    "instink",
    "inteligen",
    "jagad",
    "jahiliyah",
    "jeep",
    "jejer",
    "jemaah",
    "zarafah",
    "jiujitsu",
    "joging",
    "joint",
    "jubilum",
    "jungtur",
    "jus",
    "kaburasi",
    "kaburator",
    "kaffah",
    "kahyangan",
    "kaleidioskop",
    "kalkarim",
    "kamboja",
    "kameraman",
    "kameramen",
    "kamuplase",
    "kangguru",
    "kantung",
    "kaos",
    "kasep",
    "lajim",
    "ledeng",
    "almari",
    "lembab",
    "leukimia",
    "linier",
    "literal",
    "loby",
    "lokalisir",
    "losin",
    "maag",
    "madzab",
    "mafum",
    "mahnet",
    "maisena",
    "makdum",
    "malpraktek",
    "mampet",
    "manager",
    "mandeg",
    "margarine",
    "marjinal",
    "mas",
    "nadzar",
    "nampak",
    "nenas",
    "netralisisir",
    "nipas",
    "okulele",
    "opostrop",
    "orange",
    "orkhestra",
    "padepokan",
    "palem",
    "pamfelet",
    "panili",
    "paramedik",
    "parasit",
    "peliara",
    "pengrajin",
    "perduli",
    "philipina",
    "piara",
    "piranti",
    "plat",
    "plesetan",
    "plesir",
    "pleton",
    "plintir",
    "polio",
    "rajia",
    "rangking",
    "rangsel",
    "rapal",
    "rapot",
    "rasia",
    "rasionil",
    "realisir",
    "rekaat",
    "rekruit",
    "relif",
    "renaisan",
    "rengking",
    "reptil",
    "restauran",
    "resum",
    "reumatik",
    "rezki",
    "ridho",
    "riil",
    "rilai",
    "sahadat",
    "saklar",
    "sangkalan",
    "sanjak",
    "sansekerta",
    "saplemen",
    "sariawan",
    "score",
    "seign",
    "sekolastik",
    "sekor",
    "sekta",
    "sekterian",
    "sekuadron",
    "sekuler",
    "selektifitas",
    "selinder",
    "selulose",
    "semanda",
    "sembrono",
    "semedi",
    "sen",
    "senopati",
    "sense",
    "sentausa",
    "sentimentil",
    "sentra",
    "sepesial",
    "sepesies",
    "sepionase",
    "sepiritus",
    "seruling",
    "service",
    "setansa",
    "setriker",
    "seyogyanya",
    "shaf",
    "shampo",
    "she",
    "shogun",
    "shalat",
    "sholat",
    "silahkan",
    "silaturohmi",
    "simple",
    "sindrome",
    "sirik",
    "sirine",
    "sistim",
    "skop",
    "sky",
    "slendro",
    "sleng",
    "slenk",
    "smash",
    "sodakoh",
    "sokhib",
    "sorban",
    "sorga",
    "spagheti",
    "species",
    "srigala",
    "stagen",
    "standard",
    "standart",
    "stater",
    "stereotipe",
    "sticker",
    "stip",
    "stir",
    "stock",
    "subsidair",
    "subtansi",
    "subtitusi",
    "supermasi",
    "susastera",
    "tabligh",
    "tahta",
    "tapelak",

    "faximile",
    "inofatif",
    "kordinasi",
    "kwarter",
    "netralisir",

    "cap cai",
    "da'i",
    "da'wah",
    "export",
    "foto copy",
    "geladi resik",
    "hal-ihwal",
    "hingar-bingar",
    "i'tibar",
    "i'tikaf",
    "infra merah",
    "jor-joran",
    "ka'bah",
    "kaca mata",
    "ma'af",
    "comblang",
    "neo-kolonialisme",
    "non aktif",
    "panca indra",
    "pas photo",
    "sedia kala",
    "sub bab",
    "sub unit",
    "suka cita",
    "swa sembada",
    "syafa'at",
]

export {data_set, data_collection};
